### ISSUE TITLE
请问 运行bash ffn.sh up 出现这种错误是怎么回事？

### ISSUE THREAD

**Issue by lyh168** [meshplus/goduck#69]
bash ffn.sh up
===> Script version: 1.0
===> Download the necessary dependencies
curl: (7) Failed to connect to raw.githubusercontent.com port 443: 拒绝连接
ffn.sh: 第 52 行: cd: /go/src/github.com/meshplus/tools/fabric-samples: 没有那个文件或目录

**Comment by Alexader** [comment]
It looks like a network problem to connect github. We are using a open-source tool [fabric-sample](https://github.com/hyperledger/fabric-samples) of hyperledger in github to setup fabric network. Make sure you can connet to github.
